name: Deploy to Production S3

on: workflow_dispatch

jobs:
  deploy-production:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build the code
        run: NODE_OPTIONS=--max_old_space_size=4096 npm run build
        env:
          VITE_APP_NODE_ENV: "production"

      - name: Push to S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}/ --delete --acl public-read
